trigger: none  # Change to 'main' or another branch name to enable trigger

pool:
  name: Default  # Replace with your self-hosted agent pool name

stages:
  - stage: Sourcecode
    displayName: 'Snyk Source Code Scan Stage'
    jobs:
      - job: RunSnyk
        displayName: 'Run Snyk Scan on Local WebGoat'
        steps:
          - checkout: none  # Do not clone any repo

          - task: PowerShell@2
            displayName: 'Run Snyk Code Scan'
            inputs:
              targetType: 'inline'
              script: |
                cd "C:\Gitlab_Integration\Snyk"
                
                # Authenticate with Snyk using token from environment variable
                .\snyk-win.exe auth $env:SNYK_TOKEN

                # Run Snyk Code test on local source directory
                .\snyk-win.exe code test 'C:\Gitlab_Integration\Snyk\WebGoat-main' > 'C:\Gitlab_Integration\Report\Snyk_sourcecode.txt'

                # Allow pipeline to continue even if issues are found
                if ($LASTEXITCODE -ne 0) { 
                  Write-Host "Snyk found issues, continuing pipeline."
                  exit 0 
                }
